# Generated by Django 3.2.4 on 2021-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deActive',
            field=models.BooleanField(default=False),
        ),
    ]
